apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql
  namespace: sindan-server

<<: &job-container-template
  image: sindan/visualization:1.2.0
  env:
    - name: DB_NAME
      value: "sindan_production"
    - name: DB_GRANTED_USER
      value: "sindan"
    - name: DB_PASSWORD_FILE
      value: "/run/secrets/sindan-net.com/db_password"
    - name: RAILS_SECRETKEY_FILE
      value: "/run/secrets/sindan-net.com/rails_secret_key_base"
    - name: ACCOUNTS_FILE
      value: "/run/secrets/sindan-net.com/accounts"
  volumeMounts:
    - name: secrets
      mountPath: "/run/secrets/sindan-net.com"
      readOnly: true

spec:
  parallelism: 1
  backoffLimit: 12
  template:
    spec:
      # restartPolicy: Never
      restartPolicy: OnFailure
      containers:
        - name: migration
          <<: *job-container-template
          command: ["bundle", "exec", "rails", "db:migrate"]
        - name: seed
          <<: *job-container-template
          command: ["bundle", "exec", "rails", "db:seed"]
      volumes:
        - name: secrets
          secret:
            secretName: sindan-server-secret
            items:
              - key: db-password
                path: db_password
              - key: rails-secret-key-base
                path: rails_secret_key_base
              - key: accounts.yml
                path: accounts
