apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/pv/sindan-mysql"
---
apiVersion: v1
kind: Namespace
metadata:
  name: sindan-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sindan-server
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: sindan-server-secret
  namespace: sindan-server
type: Opaque
data:
  db-password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sindan-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "sindan_production"
            - name: MYSQL_USER
              value: "sindan"
            - name: MYSQL_PASSWORD_FILE
              value: "/run/secrets/sindan-net.com/db_password"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-secret
              mountPath: "/run/secrets/sindan-net.com"
              readOnly: true
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} -p$(cat /run/secrets/sindan-net.com/db_password)"
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 2
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-secret
          secret:
            secretName: sindan-server-secret
            items:
              - key: db-password
                path: db_password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
