apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: sindan-server
spec:
  containers:
    - image: busybox:1.28.4
      name: busybox
      command:
        - sleep
        - "360000"
      imagePullPolicy: IfNotPresent
    - image: mi2428/wait-for-it:latest
      name: waitforit
      command:
        - sleep
        - "360000"
      imagePullPolicy: IfNotPresent
    - image: sindan/visualization:1.2.0
      name: visualization
      command:
        - sleep
        - "360000"
      env:
        - name: DB_NAME
          value: "sindan_production"
        - name: DB_GRANTED_USER
          value: "sindan"
        - name: DB_PASSWORD_FILE
          value: "/run/secrets/sindan-net.com/db_password"
        - name: RAILS_SECRETKEY_FILE
          value: "/run/secrets/sindan-net.com/rails_secret_key_base"
        - name: ACCOUNTS_FILE
          value: "/run/secrets/sindan-net.com/accounts"
      volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/sindan-net.com"
          readOnly: true
      imagePullPolicy: IfNotPresent
  volumes:
    - name: secrets
      secret:
        secretName: sindan-server-secret
        items:
          - key: db-password
            path: db_password
          - key: rails-secret-key-base
            path: rails_secret_key_base
          - key: accounts.yml
            path: accounts
  restartPolicy: Never
