fluentd:
  image: sindan/fluentd:1.2.0
  pullPolicy: Always
  internetPort: 8080

mysql:
  image: mysql:5.7
  pullPolicy: IfNotPresent
  db:
    name: sindan_production
    user: sindan
    password: cGFzc3dvcmQ=
  persistence:
    size: 10Gi
    storageClassName: mysql

mysql-backup:
  cron:
    schedule: "0 * * * *"
  persistence:
    size: 10Gi
    storageClassName: mysql-backup

visualization:
  image: sindan/visualization:1.2.0
  pullPolicy: Always
  rails:
    secretKeyBase: SWYteW91LWNoYW5nZS10aGlzLXlvdS1uZWVkLXRvLWJ1aWxkLWRvY2tlcmZpbGUtbG9jYWxseQ==
  webui:
    accounts:
      - username: sindan
        emai: sindan-wg@wide.ad.jp
        password: changeme
  internetPort: 80
