apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd

<<: &healthcheck-template
  httpGet:
    path: /
    port: healthcheck
  initialDelaySeconds: 10
  periodSeconds: 1
  timeoutSeconds: 1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mi2428/wait-for-it:latest
          args: ["-q", "-t", "0", "mysql:3306", "--", "sleep", "10"]
      containers:
        - image: sindan/fluentd:1.2.0
          name: fluentd
          env:
            - name: DB_NAME
              value: "sindan_production"
            - name: DB_GRANTED_USER
              value: "sindan"
            - name: DB_PASSWORD_FILE
              value: "/run/secrets/sindan-net.com/db_password"
          ports:
            - name: healthcheck
              containerPort: 8080
            - name: fluentd
              containerPort: 8888
          volumeMounts:
            - name: fluentd-config
              mountPath: "/fluentd/etc"
              readOnly: true
            - name: fluentd-secret
              mountPath: "/run/secrets/sindan-net.com"
              readOnly: true
          livenessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
            items:
              - key: fluent.conf
                path: fluent.conf
        - name: fluentd-secret
          secret:
            secretName: sindan-server-secret
            items:
              - key: db-password
                path: db_password
