apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: sindan-server
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: mysql:5.7
              name: mysql-backup
              command:
                - sh
                - -c
                - "mysqldump -h${MYSQL_HOST} -u${MYSQL_USER} -p$(cat /run/secrets/sindan-net.com/db_password) ${MYSQL_DATABASE} > /backup/$(date +%y-%m-%d_%H:%M:%S).dump"
              env:
                - name: MYSQL_HOST
                  value: "mysql"
                - name: MYSQL_DATABASE
                  value: "sindan_production"
                - name: MYSQL_USER
                  value: "sindan"
                - name: MYSQL_PASSWORD_FILE
                  value: "/run/secrets/sindan-net.com/db_password"
              volumeMounts:
                - name: mysql-backup-pvc
                  mountPath: /backup
                - name: mysql-secret
                  mountPath: "/run/secrets/sindan-net.com"
                  readOnly: true
          volumes:
            - name: mysql-backup-pvc
              persistentVolumeClaim:
                claimName: mysql-backup-pvc
            - name: mysql-secret
              secret:
                secretName: sindan-server-secret
                items:
                  - key: db-password
                    path: db_password
