apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
  labels:
{{ include "sindan-server.labels " . | indent 4 }}
spec:
  schedule: {{ .Values.mysql-backup.cron.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
              imagePullPolicy: {{ .Values.mysql.pullPolicy }}
              name: {{ .Release.Name }}-mysql-backup
              command:
                - sh
                - -c
                - "mysqldump -h${MYSQL_HOST} -u${MYSQL_USER} -p$(cat /run/secrets/sindan-net.com/db_password) ${MYSQL_DATABASE} > /backup/$(date +%y-%m-%d_%H:%M:%S).dump"
              env:
                - name: MYSQL_HOST
                  value: {{ .Release.Name }}-mysql
                - name: MYSQL_DATABASE
                  value: {{ .Values.mysql.db.name }}
                - name: MYSQL_USER
                  value: {{ .Values.mysql.db.user }}
                - name: MYSQL_PASSWORD_FILE
                  value: "/run/secrets/sindan-net.com/db_password"
              volumeMounts:
                - name: mysql-backup-pvc
                  mountPath: /backup
                - name: mysql-secret
                  mountPath: "/run/secrets/sindan-net.com"
                  readOnly: true
          volumes:
            - name: mysql-backup-pvc
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-mysql-backup-pvc
            - name: mysql-secret
              secret:
                secretName: {{ .Release.Name }}-secret
                items:
                  - key: db-password
                    path: db_password
