apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sindan-server
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: sindan-server
spec:
  storageClassName: mysql-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
