apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{ include "sindan-server.labels " . | indent 4 }}
type: Opaque
data:
  db-password: {{ .Values.mysql.db.password }}
  rails-secret-key-base: {{ .Values.visualization.rails.secretKeyBase }}
stringData:
  accounts.yml: |-
    accounts:
      - username: sindan
        email: sindan-wg@wide.ad.jp
        password: changeme
