apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{ include "sindan-server.labels" . | indent 4 }}
type: Opaque
data:
  db-password: {{ .Values.mysql.db.password }}
  rails-secret-key-base: {{ .Values.visualization.rails.secretKeyBase }}
stringData:
  accounts.yml: |-
    accounts:
{{ range .Values.visualization.webui.accounts }}
      - username: {{ .username }}
        email: {{ .email }}
        password: {{ .password }}
{{- end }}
