apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-password: {{ .Values.mysql.db.password }}
  rails-secret-key-base: {{ .Values.visualization.rails.secretKeyBase }}
stringData:
  accounts.yml: |-
    accounts:
      - username: sindan
        email: sindan-wg@wide.ad.jp
        password: changeme
