apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fluentd-service
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: fluentd
      protocol: TCP
      port: 8080
      targetPort: {{ .Values.fluentd.servicePort }}
  selector:
    app: fluentd
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: visualization
spec:
  ports:
    - name: visualization
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: visualization
