apiVersion: v1
kind: Service
metadata:
  name: fluentd
spec:
  ports:
    - port: 8080
  selector:
    app: fluentd

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: visualization
spec:
  ports:
    - port: 3000
  selector:
    app: visualization
