apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization
  # namespace: sindan-server

<<: &container-template
  image: sindan/visualization:1.2.0
  env:
    - name: DB_NAME
      value: "sindan_production"
    - name: DB_GRANTED_USER
      value: "sindan"
    - name: DB_PASSWORD_FILE
      value: "/run/secrets/sindan-net.com/db_password"
    - name: RAILS_SECRETKEY_FILE
      value: "/run/secrets/sindan-net.com/rails_secret_key_base"
    - name: ACCOUNTS_FILE
      value: "/run/secrets/sindan-net.com/accounts"
  volumeMounts:
    - name: secrets
      mountPath: "/run/secrets/sindan-net.com"
      readOnly: true

spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: visualization
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mi2428/wait-for-it:latest
          args: ["-q", "-t", "0", "mysql:3306", "--", "sleep", "10"]
        - name: rails-db-migrate
          <<: *container-template
          command: ["bundle", "exec", "rails", "db:migrate"]
        - name: rails-db-seed
          <<: *container-template
          command: ["bundle", "exec", "rails", "db:seed"]
      containers:
        - name: visualization
          <<: *container-template
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          ports:
            - name: webrick
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /users/sign_in
              port: webrick
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /users/sign_in
              port: webrick
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 2
      volumes:
        - name: secrets
          secret:
            secretName: sindan-server-secret
            items:
              - key: db-password
                path: db_password
              - key: rails-secret-key-base
                path: rails_secret_key_base
              - key: accounts.yml
                path: accounts
